### ISSUE TITLE
All Villagers are Named Moog

### ISSUE THREAD

**Issue by gigawhip** [FinnSetchell/MoogsVanillaStructuresV2#10]
Every villager is named "Moog" or "moog" causing a minor issue with the popular [Villager Names](https://beta.curseforge.com/minecraft/mc-mods/villager-names) mod. That mod assigns unique names to each villager so they have more individuality and are easier to remember. In that context, encountering any MVS villager house gives the strange feeling that you've entered a house of clones.

Additionally vanilla villagers are unnamed, so it stands out when you find these Moogs even without Villager Names, making them feel distinctly "modded" rather than blending in with vanilla.

![image](https://user-images.githubusercontent.com/103098495/222934511-5dcfbcce-e2c7-4dfc-86cd-37fbb8754c10.png)

**Comment by FinnSetchell** [comment]
Thanks. After a few of these complaints, I've removed the names from all villagers now :)
