### ISSUE TITLE
Several Structures Appear to be Missing Villagers

### ISSUE THREAD

**Issue by gigawhip** [FinnSetchell/MoogsVanillaStructuresV2#11]
Each of the following structures appears to be not-abandoned, some even actively lived-in, but they do not contain any villagers. Unclear if this in intentional, if the structures are unfinished, or if this was accidental.

- all stalls
- `mvs:beachbar`
- `mvs:beedome`
- `mvs:campsite`
- `mvs:horsepen`

**Comment by FinnSetchell** [comment]
thanks, I've added/removed villagers to all structures to make it feel a bit better now.
