### ISSUE TITLE
Moog's voyagers structures with Terralith generation

### ISSUE THREAD

**Issue by Xanatosxx** [FinnSetchell/MoogsVanillaStructuresV2#12]
Hi, 

I recently play on a modpack with both mods install, problem is i can't find any structures in my world. 
My question is : is it allowed to structures to spawn based on biome tags, rather than individual biomes ?

**Comment by FinnSetchell** [comment]
Hi, ive removed the biome tags now as it resulted in too unpredictable generation (you can ofc add these back with the config pack). However from my testing with terralith, the structures did generate fine in terralith biomes. The structures are intended to be rare so you may not find many in survival but they should be there. Try running /locate structure to find some.

**Comment by FinnSetchell** [comment]
If that doesnt work, please send a debug-log and ill have a look

**Comment by Xanatosxx** [comment]
Ok i tried to do what you said and found structures !  But they are really far away from the spawn (2000blocks). Is there any reason behind this ?

**Comment by FinnSetchell** [comment]
Many of the structures are intended to be rare, but it sounds like you could have just gotten a bit unlucky with the seed

**Comment by Xanatosxx** [comment]
Possible. 
Thx for helping !

**Comment by FinnSetchell** [comment]
No worries, and remember you can increase the spawning rates using the config pack linked on the mod page
