### ISSUE TITLE
Reference To Unknown Structure [1.19.2]

### ISSUE THREAD

**Issue by LunarDev-git** [FinnSetchell/MoogsVanillaStructuresV2#13]
# Client Information

MC Version: 1.19.2
Modloader Version: 43.2.8
Mod Version: mvs-3.1-mvs-1.19.2.jar

## Description of the bug

Ever since the big changes I've been getting these logs in my console

![image](https://user-images.githubusercontent.com/105180230/233808085-0fd27806-332f-4fa1-ae82-b6f3ea9fb6e0.png)

**Comment by FinnSetchell** [comment]
Are you using any data packs that could be referencing the mod? As the names and directories have changed, data packs will have to be updated.
Otherwise, could you send a log for me to look at?
Thanks

**Comment by LunarDev-git** [comment]
I used to use a datapack that basically just reduced some of the "spawn rates" of structs but I deleted them, Do these warnings just go away? I can upload a log if still needed based on this new information

**Comment by FinnSetchell** [comment]
if you've removed the data pack and are still having issues then yes please, send a log.

**Comment by LunarDev-git** [comment]
[latest.log](https://github.com/FinnSetchell/MoogsVoyagerStructures/files/11302527/latest.log)

Edit: Here's another log 23/04
[latest2.log](https://github.com/FinnSetchell/MoogsVoyagerStructures/files/11304644/latest.log)


Hopefully this does the trick, if it doesn't I'll be happy to provide anything I can

**Comment by FinnSetchell** [comment]
hiya, sorry for the wait.
So this is caused by previously loaded structures from old versions due to the new names. From my testing, it doesn't seem to create any issues and should be fine to ignore. If you can you should use something like MCA Selector to trim unused chunks from your world so new features can generate and delete the old structures.

**Comment by SplendidAlakey** [comment]
If you can't reproduce [this bug](https://bugs.mojang.com/browse/MC-194811), you should be ok.

To get rid of the log spam you can use something like [Log Begone](https://modrinth.com/mod/log-begone) or remove any existing references from the .mca files either manually with [NBTExplorer](https://github.com/jaquadro/NBTExplorer) or automatically with [MCStructureCleaner](https://github.com/Nyveon/MCStructureCleaner). Note: for the manual process you'd have to only touch the files, that contained the deleted structures, and for the automatic one - I'm not sure if the script still works on 1.19. The best way is to probably just filter the logs out, if log spam is the only issue you are having.

**Comment by FinnSetchell** [comment]
Thanks @SplendidAlakey that was really useful!
From further testing I've found that the world doesn't have any issues saving or any of the other issues outlined [here](https://bugs.mojang.com/browse/MC-194811). @MoonstruckSpirit I would recommend using Log Begone and/or trying out MCStructureCleaner

**Comment by LunarDev-git** [comment]
This was really helpful! Thank you loads! However since I can see it’s pretty much me I will close the issue ♡
