### ISSUE TITLE
Chests problems in campsite

### ISSUE THREAD

**Issue by ghost** [FinnSetchell/MoogsVanillaStructuresV2#14]
mvs:other_decoration/campsite has these two chests under the roof that you need to break to open them. Maybe translate them into barrels?
![2023-05-02_03 43 58](https://user-images.githubusercontent.com/124847943/235499718-29f07026-a26c-43ab-ad32-5365b34f4ee4.png)

**Comment by FinnSetchell** [comment]
yup, ill do that for the next update
