### ISSUE TITLE
Saw some weird error on my game log I'm not sure if this is important but I thought I'd share

### ISSUE THREAD

**Issue by Minebrah** [FinnSetchell/MoogsVanillaStructuresV2#15]
https://gist.github.com/Minebrah/e74e533c2d667f695add184f55b30675

**Comment by FinnSetchell** [comment]
I'm guessing its from a json, ill look into it asap.

**Comment by Minebrah** [comment]
awesome

**Comment by FinnSetchell** [comment]
this has been resolved for the next update
