### ISSUE TITLE
Bug - Registry empty & Cannot load Tags

### ISSUE THREAD

**Issue by Yourname942** [FinnSetchell/MoogsVanillaStructuresV2#16]
**Bug Description**
Registry mvs:json_conditions' is empty:
![image](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/58750222/abc32e2c-8752-4e52-9856-c0e8b5d46789)

Cannot load tags:
![image](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/58750222/9587250b-3b02-4701-bf78-985f4168a2b9)

**Steps to Reproduce**
1. Open Curseforge app
2. Create a new profile
3. MC 1.19.2
4. Forge 43.2.11
5. Install JEI
6. Install MVS 3.2
7. launch the game
8. create a new world (creative/hard)
9. enter the world
10. close the game
_observe the errors in the log file_

MC 1.19.2
Forge 43.2.11
MVS 3.2

Latest log: https://paste.ee/p/eOeoB

**Comment by FinnSetchell** [comment]
This is just forge log spam. You can ignore it
