### ISSUE TITLE
Water Logging Structures

### ISSUE THREAD

**Issue by FinnSetchell** [FinnSetchell/MoogsVanillaStructuresV2#17]
structures like the wells are getting waterlogged stairs

**Comment by OfficialLahusa** [comment]
Had this issue too, especially with `mvs:well/small_well`, which usually causes flooding in the surrounding area

**Comment by SiverDX** [comment]
if you're using certain mods from yung or integrated dungeons etc. you can use their waterlogging processor and apply them to the processor list of the problematic structures

e.g.

``` json
{
  "processors": [
    {
      "processor_type": "integrated_api:waterlogging_fix_processor"
    }
  ]
}
```

**Comment by Cyan4235** [comment]
> if you're using certain mods from yung or integrated dungeons etc. you can use their waterlogging processor and apply them to the processor list of the problematic structures
> 
> e.g.
> 
> ```json
> {
>   "processors": [
>     {
>       "processor_type": "integrated_api:waterlogging_fix_processor"
>     }
>   ]
> }
> ```

Could you expand on how to do this?
