### ISSUE TITLE
Server Hang No Resolve/World Generate Issue

### ISSUE THREAD

**Issue by ChosenArchitect** [FinnSetchell/MoogsVanillaStructuresV2#18]
**Issue** 
When traveling to a MVS structure it will cause the server to hand and if loading a new world and the structure is in the spawn it will prevent the world from fully loading/

**Version** 
- mvs-4.1-1.20.jar

**Server Log**
- https://pastebin.com/vZfnYryA

**Comment by SiverDX** [comment]
install modernfix it will do a thread dump providing more information once the server starts hanging behind

**Comment by ChosenArchitect** [comment]
I am using modernfix-forge-5.8.1+mc1.20.1

**Comment by SiverDX** [comment]
how long did you wait after the last log entry in there

**Comment by ChosenArchitect** [comment]
till after the server timed me out
it is repeatable and then the server rolls back
after removing MVS the server works fine and going back to that location works just fine

**Comment by FinnSetchell** [comment]
I cant seem to re-create this, installed your modpack and updated mvs. I can go to all structures fine

**Comment by ChosenArchitect** [comment]
This was on the update when I was testing. I am getting a lot of people having the same issue and that's if they can even load the world for the first time. I wish there was more information other then a few screenshots I have of when it was happening.
![2023-10-19_10 00 37](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/35053440/916eaa19-f5ad-43ff-9987-ed0a156df812)
![2023-10-19_10 00 39](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/35053440/7777226d-fc79-4df1-bdcc-2cc6316f021b)
![2023-10-19_10 00 58](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/35053440/829121a8-82d6-4b9c-a15e-a587d2a4b344)

**Comment by ChosenArchitect** [comment]
those were all next to each other when the server was in limbo after going to them

**Comment by ChosenArchitect** [comment]
I know I did try and open that chest in the hut with the terracotta roof and after that everything stoped

**Comment by SiverDX** [comment]
![image](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/22003703/c724509d-c48b-438e-95bd-1098ec5fff8d)

enable this in modernfix config and make sure modernfix is also present on the server if its hosted

**Comment by ChosenArchitect** [comment]
this is a local server to test the server files for export

**Comment by ChosenArchitect** [comment]
ill give it a shot and see if I can recreate the issue

**Comment by FinnSetchell** [comment]
hmm maybe its certain structures? i froze when i went to the wheat farm

**Comment by ChosenArchitect** [comment]
So this is the server log with the mixin as the issue happened again
[latest.log](https://github.com/FinnSetchell/MoogsVoyagerStructures/files/13044796/latest.log)

**Comment by SiverDX** [comment]
looks like unsafe chunk handling from https://www.curseforge.com/minecraft/mc-mods/nomowanderer
is there a wanderer in any of the structures? if yes then the mod would have problems with any wanderer which gets placed during world gen

you can check its git for similar issues

```log
	at TRANSFORMER/nomowanderer@1.20.1_1.6.0/nomowanderer.world.EntitySpawnHandler.getChunksInRadius(EntitySpawnHandler.java:206)
	at TRANSFORMER/nomowanderer@1.20.1_1.6.0/nomowanderer.world.EntitySpawnHandler.checkBlockEntities(EntitySpawnHandler.java:152)
	at TRANSFORMER/nomowanderer@1.20.1_1.6.0/nomowanderer.world.EntitySpawnHandler.checkSpawn(EntitySpawnHandler.java:65)
	at TRANSFORMER/nomowanderer@1.20.1_1.6.0/nomowanderer.world.EntitySpawnHandler.maybeChangeEntitySpawn(EntitySpawnHandler.java:39)
	at TRANSFORMER/nomowanderer@1.20.1_1.6.0/nomowanderer.world.__EntitySpawnHandler_maybeChangeEntitySpawn_EntityJoinLevelEvent.invoke(.dynamic)
```
