### ISSUE TITLE
[Forge - 1.19.2]: Hard-coded loot tables

### ISSUE THREAD

**Issue by SiverDX** [FinnSetchell/MoogsVanillaStructuresV2#19]
Not sure if they're intentional but they make things a bit annoying for modpacks
(Since often times you're replacing / modifying what spawns in chests etc. but thats not really feasible when the loot is defined within the `.nbt` file itself)

I think it's more common in the newly added structures

**Example**: `mvs:other_decoration/pile`
Which by the way is defined to spawn quite often and has way too many emeralds

**Comment by FinnSetchell** [comment]
ye those are just temporary until I have time to set them up with loot tables. Just wanted to get the update out before i had no time again xD

**Comment by FinnSetchell** [comment]
I will also be swapping out the ones using vanilla loot tables to custom ones

**Comment by FinnSetchell** [comment]
resolved, just going through some more issues before i release
