### ISSUE TITLE
World Gen Issue with IDAS (Integrated Dungeons and Structures)

### ISSUE THREAD

**Issue by TheSpartan696** [FinnSetchell/MoogsVanillaStructuresV2#21]
![image](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/127004713/fe965691-bbde-4205-a454-c922b590b678)
 Was messing with my modpack and found this. MVS Structure Conflicting with IDAS structure.

**Comment by FinnSetchell** [comment]
Unfortunately in order to create efficient world generation we can't always check for other structures. As such, occassionally structures will spawn on top of each other.
