### ISSUE TITLE
End City Loot Tables used in Overworld Structures

### ISSUE THREAD

**Issue by fzzyhmstrs** [FinnSetchell/MoogsVanillaStructuresV2#24]
The Large Warped Tower (at least) uses a chest with the End City Chest loot table in it. This breaks some of the progression of my mod (and possibly others) by giving them access to loot that is *only supposed to be found in the end* two dimensions early.

**PLEASE** use only overworld chest loot tables for overworld structures, or consider making a custom loot table with the type of gear you want to be present in it.

This item is not supposed to be found this easily. It being here unlocks end game progressions hours and hours and hours before I want it to be
![Screenshot 2023-11-01 180936](https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/72876796/1fe29f05-7026-47ea-a201-74e1ef77eb6f)

**Comment by FinnSetchell** [comment]
Yup this is temporary, will be making my own loot tables top priority.

**Comment by FinnSetchell** [comment]
Ill see if I can get it out by the weekend

**Comment by FinnSetchell** [comment]
resolved. will release later tonight with any luck
