### ISSUE TITLE
Weird and Unnatural Structure Placement [Fabric 1.19.2/0.14.25]

### ISSUE THREAD

**Issue by pokesmells** [FinnSetchell/MoogsVanillaStructuresV2#30]
https://github.com/FinnSetchell/MoogsVoyagerStructures/assets/33227568/e6d6cd61-3d3d-4bd2-b6a4-77e2201b47e7

[latest.log](https://github.com/FinnSetchell/MoogsVoyagerStructures/files/13565484/latest.log)

**Comment by pokesmells** [comment]
This happens with other structures within the mod as well.

**Comment by SiverDX** [comment]
thats just how structures work

https://github.com/FinnSetchell/MoogsVoyagerStructures/blob/1.20-MultiLoader/common/src/main/resources/data/mvs/worldgen/structure/other_decoration/mine_with_campsite.json

you can try setting 

```json
  "terrain_height_radius_check": 1,
  "allowed_terrain_height_range": 3,
```

and play around with `allowed_terrain_height_range`
the radius check 1 means it checks 9 chunks (structure placement and the chunks around it) so i'd recommend not increasing it

having too low values can make the structure pretty somewhat rare though
