### ISSUE TITLE
floating island with house not generating 1.20.1 forge

### ISSUE THREAD

**Issue by commanderdarkkirby** [FinnSetchell/MoogsVanillaStructuresV2#31]
this structure used to work just fine but for some reason it is refusing to spawn. and the place command doesn't even work at all even though i don't get an error when using the place structure command. i did uninstall the other mods and only used this mod and the required one to check if it was some conflict but no it wasn't and the issue is still there

**Comment by senselessenvelope** [comment]
can confirm this is an issue in 1.19.2 version 4.1 and above, but the version just below (3.2) works, so something in updating 3.2 to 4.1 broke it

**Comment by DanteTooMayCry** [comment]
I can confirm too. Plus deepslate house too

**Comment by kr1sal** [comment]
Fabric 1.20.1 too. I can't open large_floating_island.nbt, but i think problem in supplementaries (error log with render visual book)

**Comment by FinnSetchell** [comment]
The nbt was corrupt. This has been fixed for the next update.
