### ISSUE TITLE
1.20.1 World Not Loading/Creating

### ISSUE THREAD

**Issue by xd4rkzghost01** [FinnSetchell/MoogsVanillaStructuresV2#33]
Hello there ! I'vee encounter this issue with those 2 mod. When trying to boot up a new/old world, i get stuck to the dirt screen and can't load anything and we've force to quit the game. I'm writting this while testing it, so it could not be your side but i've warn the other 2 said mod and they said it come from yours.

Minecraft **1.20.1**
Forge **47.2.20**
Blueprint **7.0.1**
OuterEnd **1.0.7**
MoogEnd **1.3**
MoogVS **4.1.1**
and _**150**_ other mod

### Various Crash and Log
[Log with all the mod on](https://github.com/FinnSetchell/MoogsEndStructures/files/14541291/latest.log)
[Force Crash to quit](https://github.com/FinnSetchell/MoogsEndStructures/files/14541286/crash-2024-03-08_12.20.29-server.txt)

[Log Without The OuterEnd](https://github.com/FinnSetchell/MoogsEndStructures/files/14541354/latest.log)
[ForceCrash without OuterEnd](https://github.com/FinnSetchell/MoogsEndStructures/files/14541361/crash-2024-03-08_12.33.35-server.txt)

[Log Without MES](https://github.com/FinnSetchell/MoogsEndStructures/files/14541439/2024-03-08-3.log)
[ForceCrash Without MES](https://github.com/FinnSetchell/MoogsEndStructures/files/14541428/crash-2024-03-08_12.39.26-server.txt)

And finally ! i found that it's the main one, Moog's Voyager Structure
[Log Without MVS](https://github.com/FinnSetchell/MoogsVoyagerStructures/files/14541510/latest.log)

And no crash this time. The game load perfectly.
I love this structure Mod but the End seem so empty so i like to have OuterEnd too but, seem like MVS is crashing the game soooo, if you could take a look :D

**Comment by TheNamesJames** [comment]
same issue here

**Comment by FinnSetchell** [comment]
the mod was incompatible with blueprint. I have now fixed this and will release the update soon
