### ISSUE TITLE
[Crash] [1.20.1] Incompatibility with Blueprint 7.0.1

### ISSUE THREAD

**Issue by oitsjustjose** [FinnSetchell/MoogsVanillaStructuresV2#34]
I'm sure you've already seen this [here](https://github.com/FinnSetchell/MoogsEndStructures/issues/6), but in case you haven't (since that seems to be the wrong repo I think?) I wanted to forward the issue over to this repo - looks like [this bug on the TeamAbnormals repo](https://github.com/team-abnormals/blueprint/issues/226) contains a good bit of technical detail as to how the asset loading is causing the issue. I've been able to confirm that disabling MVS makes it so I'm able to load my world again.

**Comment by TheNamesJames** [comment]
same issue here

**Comment by FinnSetchell** [comment]
Thanks for the help. I believe i have fixed this issue now and will be releasing an update for it soon
