### ISSUE TITLE
client side or server side?

### ISSUE THREAD

**Issue by VaporeonScripts** [FinnSetchell/MoogsVanillaStructuresV2#37]
hi, im using all 3 of ur mods but only nether and end one are marked as only needed for server side, while overworld one is marked as both client and server side, but as said by u, it uses vanilla blocks, so, is it needed for both client and server or only server?

**Comment by FinnSetchell** [comment]
only server, must have accidently marked it as both. Thanks, ill update it now.

**Comment by VaporeonScripts** [comment]
Ok,ty
