### ISSUE TITLE
Removed the mod, now it wont let me create a new world [Fabric 1.19.2]

### ISSUE THREAD

**Issue by lxly9** [FinnSetchell/MoogsVanillaStructuresV2#6]
[crash-2022-12-03_13.14.17-client.txt](https://github.com/FinnSetchell/MoogsVoyagerStructures/files/10146350/crash-2022-12-03_13.14.17-client.txt)
This is the fancy issue im getting after removing the mod from my mods folder. Im trying to make a *new* world and it crashes upon clicking create new world.

**Comment by FinnSetchell** [comment]
did you definitely restart mc after removing it?

**Comment by FinnSetchell** [comment]
im doing some tests now to try and recreate the issue

**Comment by lxly9** [comment]
i know what the issue was, the datapack with the values for the structures. Added it into one of mine and forgot about it.

**Comment by FinnSetchell** [comment]
was just about to ask if u were using a datapack lol
