### ISSUE TITLE
Missing lines and characters in "Master Sun's Art of War" written book

### ISSUE THREAD

**Issue by Apot98** [FinnSetchell/MoogsVanillaStructuresV2#7]
Minecraft version: 1.19.2
Fabric version: 0.14.11
MVS version: v2.5.10-1.19.2

The written book "Master Sun's Art of War" in structure sunzigate.nbt has lines missing in several pages, possibly due to having too many lines in these pages, resulting last lines in these pages omitted. For example, in chapter "Laying Plans", the line ”地者，远近、险易、广狭、死生也。“ is missing between page 2 and page 3, and ”味不过五，五味之变，不可胜尝也；“ is missing between page 15 and 16. Also there's some uncommon characters missing, like ”芑“ in ”芑秆一石，当吾二十石。“ in page 7.

**Comment by FinnSetchell** [comment]
thanks for the feedback however there's not much we can do about this. It automatically omitted a few characters to fit into the book format and a few rare characters could not be written
