### ISSUE TITLE
Pathfinding Issues in Villager Houses

### ISSUE THREAD

**Issue by gigawhip** [FinnSetchell/MoogsVanillaStructuresV2#8]
In the following structures which include villagers, some aspects of the structure prevent the villagers from navigating properly, often permanently stranding them in their bedrooms. In all cases, trap doors, slabs, and/or ladders are causing the problems.

## Test Environment

Minecraft 1.19.2, recommended Forge version 43.2.0, MVS 3.1.6 with no other mods installed.

## `mvs:azaleahouse`

Villagers are stuck upstairs, thrown off by a trap door which is not in their way. Breaking the trap door fixes the issue.

![image](https://user-images.githubusercontent.com/103098495/222933702-c6725984-083d-4acb-96de-73d05cead9e8.png)

![image](https://user-images.githubusercontent.com/103098495/222933735-5866b75b-de34-4840-adfc-a90aa926bb07.png)

## `mvs:barn`

Villagers are stuck upstairs.

![image](https://user-images.githubusercontent.com/103098495/222933148-24ae2654-0ec6-4e08-bddf-ac9e129892ff.png)

## `mvs:deepslatehouse`

Villagers are unable to leave the attic. They cannot pathfind down the ladder from the slab floor. They get stuck trying to jump out the brick stair windows. If you break the trap doors under the ceiling barrels, they congregate at the brick stair window. If you break open the wall, they jump out the opening and pathfind to first story of the house, revealing that they were trying to go downstairs all along. Additionally they cannot enter the beds at night.

![image](https://user-images.githubusercontent.com/103098495/222934353-34fdcc97-bbf7-4023-ba7f-9571284d410a.png)

## `mvs:flowerhole`

Villagers are stuck on "table".

![image](https://user-images.githubusercontent.com/103098495/222933416-149b220c-fdad-4c94-b0e0-48c13da1ceae.png)

## `mvs:tallhouse`

Villagers are stuck in attic.

![image](https://user-images.githubusercontent.com/103098495/222933495-c082e754-f48b-4327-928b-15ab36d94233.png)

## `mvs:warpedhouse`

Villagers cannot recognize beds (trap door side tables) and cannot find Composter workstations despite being spawned as farmers. Result is that they immediately start pathfinding away from the house even at night, resulting in their swift death by zombies.

![image](https://user-images.githubusercontent.com/103098495/222933596-99aa6374-717f-4031-b27d-0cb5e5faabaf.png)

**Comment by FinnSetchell** [comment]
thanks, ill go through these issues tomorrow 👍

**Comment by FinnSetchell** [comment]
I've now added lecturns or other profession blocks to prevent the villagers from trying to pathfind to barrels far away.
